# NUMPY 

In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x, type(x), x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [9]:
x = np.arange(2,20, 3)
print(x)

[ 2  5  8 11 14 17]


In [10]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.linspace(1,21,3)

array([ 1., 11., 21.])

In [13]:
x = np.arange(1,16)
print(x, x.shape)  

x.reshape(5,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] (15,)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [14]:
np.random.rand(2,3)
## 0, 1사이의 분포로 랜덤한 ndarray 생성

array([[0.61137923, 0.65732776, 0.12329161],
       [0.80412599, 0.13482838, 0.68904286]])

In [15]:
np.random.randn(2,3)
## 정규분포로 샘플링된 랜덤 ndarray 생성

array([[-0.38009328,  1.17782622,  1.91132424],
       [-0.93923264, -0.97299826,  2.17520688]])

In [16]:
np.random.randint(1,100,(3,5)) 
## 1~99사이의 정수로 이루어진 3x5 행렬 생성

array([[37, 11, 45,  3, 65],
       [46, 44, 69, 56, 58],
       [49, 85, 30, 38, 26]])

In [17]:
np.random.choice(100, (3, 4))  
## random.arange(0,100) 즉, 0~99사이의 랜덤숫자로 3x4 행렬 생성

array([[17, 78, 58, 25],
       [29, 29, 45, 67],
       [47,  9, 55, 78]])

In [18]:
x = np.arange(10).reshape(2, 5)
print(x,"   ", x[0][3],"   ", x[0:1,2:4])

[[0 1 2 3 4]
 [5 6 7 8 9]]     3     [[2 3]]


In [19]:
x = np.arange(24).reshape(2, 3, 4)
print(x)
print("")
print(x[:1,:2,:])  ## 슬라이싱만 해서 차원 유지
print("")
print(x[0,:2,:] )  ## 인덱싱 한번해서 한 차원 줄어듬

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[0 1 2 3]
  [4 5 6 7]]]

[[0 1 2 3]
 [4 5 6 7]]


- ravel과 flatten은 n차원을 1차원으로 바꿔준다

    - ravel은 기존의 것 그대로 사용  
    - flatten은 기존의 것을 복사해서 사용

In [20]:
x = np.arange(6).reshape(2,3)
print(x.flatten())
print(x.ravel())

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [21]:
x1 = np.array(([1,2,3],[4,5,6]))
x2 = np.arange(6).reshape(2,3)
print(x1)
print("")
print(x2)
print(np.mean(x1))
print(np.sum(x1))
print(np.max(x1))
print(np.argmax(x1))

[[1 2 3]
 [4 5 6]]

[[0 1 2]
 [3 4 5]]
3.5
21
6
5


- any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [22]:
x = np.array(([1,2,-4],[4,5,6]))

print(np.all(x>0))
print(np.any(x>0))

False
True


In [23]:
x = np.array(([1,2,-4],[4,-1,6]))
np.where(x>0, x, 0)

array([[1, 2, 0],
       [4, 0, 6]])

### 1차원 벡터  (행의 Transpose) -> axis = 0
    - axis=None은 axis=0과 동일
    - axis=0 -> 행이 증가하는방향(오른쪽)으로 연산
    - 이때는 transpose된 것으로 나오므로 행이 증가하는 방향이 오른쪽 
### 2차원 행렬 (행 x 열)-> axis = 0 or 1
    - axis=None은 axis=0,1과 동일
    - axis=None ->(기본값).. 행,열 둘다 증가하는 방향으로 연산(오른쪽 아래로)
    - axis=0 -> 행이 증가하는 방향(밑으로) 연산.... shape(a,b)중 a 기준
    - axis=1 -> 열이 증가하는 방향(오른쪽으로) 연산.... shape(a,b)중 b 기준
### 3차원 텐서 (행렬 x 행 x 열)-> axis = 0 or 1 or 2
    - axis=None은 axis=0,1,2와 동일
    - axis=None -> (기본값).. 전부다 연산  -> 결과는 숫자 하나
    - axis=1 -> shape(a,b,c)에서 a기준으로 연산 -> 결과는 bxc행렬
    - axis=2 -> shape(a,b,c)에서 b기준으로 연산 -> 결과는 axc행렬
    - axis=3 -> shape(a,b,c)에서 c기준으로 연산 -> 결과는 axb행렬

In [24]:
z = np.arange(24).reshape(2,3,4)
print(np.sum(z),"\n")
print(np.sum(z, axis=0),"\n")
print(np.sum(z, axis=1),"\n")
print(np.sum(z, axis=2),"\n")
print(np.sum(z, axis=(0,2)),"\n")
print(np.sum(z, axis=(0,1,2)))

276 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[12 15 18 21]
 [48 51 54 57]] 

[[ 6 22 38]
 [54 70 86]] 

[ 60  92 124] 

276


### broascasting
- **뒷 차원**에서 부터 비교하여 **Shape이 같거나**, 차원 중 **값이 1인 것**이 존재하면 가능
     - (4,3)과 (1,3) 가능    <- 3=3 and 1존재
     - (4,3)과 3 가능        <- 3=3 and 1존재
     - (4,3)과 (1,4) 불가능  <- 3!=4
     - (4,3)과 (2,3) 불가능  <- 3=3 but 4!=2

### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

In [25]:
x = np.random.randint(1,101, size=10)
print(x,"\n")
print(x % 2 == 0,"\n")
print(len(x % 2 == 0),"\n")
print(x[x % 2 == 0],"\n")
x[(x % 2 == 0) & (x > 30)]

[59 75 12  9 29  4 66 74 24 81] 

[False False  True False False  True  True  True  True False] 

10 

[12  4 66 74 24] 



array([66, 74])

In [26]:
x1 = np.random.rand(2,3)
x2 = np.arange(6).reshape(3,2)
np.matmul(x1,x2) # 벡터곱

array([[1.30368425, 2.45939546],
       [4.08403937, 6.21893387]])

In [27]:
## 1. 로또번호 생성기

np.random.randint(1,46,6) ## 중복발생

np.random.choice(np.arange(1,46), size=6, replace=False)  ## 중복 제거

array([29, 30, 35, 27, 15, 28])

In [28]:
## 2. 파이 계산하기 (몬테카를로 방법)

count = int(1e7)
x = np.random.rand(count)
y = np.random.rand(count)
num = np.sqrt(x**2 + y**2) <= 1
pi = (np.sum(num) / count) * 4
pi

3.1403132