## Clustering: grouping observations together

### 1. K-means clustering

In [1]:
from sklearn import cluster, datasets

X_iris, y_iris = datasets.load_iris(return_X_y=True)
k_means = cluster.KMeans(n_clusters=3)
k_means.fit(X_iris)

KMeans(n_clusters=3)

In [12]:
k_means.labels_[::10]

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2])

In [3]:
y_iris[::10]

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

## Decompositions: from a signal to components and loadings

### 1. Principal component analysis: PCA

In [16]:
import numpy as np

x1 = np.random.normal(size=100)
x2 = np.random.normal(size=100)
x3 = x1 + x2
X = np.c_[x1, x2, x3]
X[:3]

array([[-0.59486936, -0.29006015, -0.88492951],
       [-0.8867501 , -1.89703471, -2.78378482],
       [-1.13120957,  1.55072654,  0.41951697]])

In [19]:
from sklearn import decomposition

pca = decomposition.PCA()
pca.fit(X)

pca.explained_variance_
 # As we can see, only the 2 first components are useful

array([2.71970949e+00, 1.05912661e+00, 2.22913804e-32])

In [20]:
pca.n_components = 2
X_reduced = pca.fit_transform(X)
X_reduced.shape

(100, 2)