### 학습목표
 1. 인덱싱과 슬라이싱 활용하기


In [29]:
import numpy as np

## 인덱싱을 하면 차원이 하나 줄어든다!!
## 슬라이싱을 하면 차원이 그대로 유지된다!!

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(x[2:4])

[2 3]


* 2차원 행렬 인덱싱

In [16]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
print(x[0][3])

x[0,3] ## 위와 동일

3


3

* 3차원 텐서 인덱싱

In [20]:
x = np.arange(60).reshape(3, 4, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [21]:
print(x[1][2][0])

x[1,2,0] ## 위와 동일

30


30

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [23]:
x = np.arange(10)

In [25]:
x[1:5]

array([1, 2, 3, 4])

* 2차원 행렬 슬라이싱

In [26]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
x[:,2:4]

array([[2, 3],
       [7, 8]])

* 3차원 텐서 슬라이싱

In [30]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [33]:
x[:1,:2,:]   ## 슬라이싱만 해서 차원 유지

array([[[0, 1, 2],
        [3, 4, 5]]])

In [34]:
x[0,:2,:]   ## 인덱싱 한번해서 한 차원 줄어듬

array([[0, 1, 2],
       [3, 4, 5]])