## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [6]:
x = np.random.rand(3,3)
print(x)

print(np.matmul(x, np.linalg.inv(x)))  ## x 곱하기 x의 역행렬
print(x @ np.linalg.inv(x))  ## 2가지 방식으로 행렬곱 표현 가능


[[0.91278938 0.79026725 0.69083923]
 [0.51576159 0.92199291 0.42217558]
 [0.31821452 0.64786114 0.08830001]]
[[ 1.00000000e+00  6.57023638e-16 -2.18279096e-16]
 [-1.33127918e-16  1.00000000e+00 -1.06511285e-16]
 [ 8.19831822e-17  2.08036664e-16  1.00000000e+00]]
[[ 1.00000000e+00  6.57023638e-16 -2.18279096e-16]
 [-1.33127918e-16  1.00000000e+00 -1.06511285e-16]
 [ 8.19831822e-17  2.08036664e-16  1.00000000e+00]]


#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 닭의 합 : 25 호랑이 다리와 닭 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [12]:
A = np.array([[1,1], [2,4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [13]:
## Ax = B가 맞는지 검산
## 컴퓨터 계산시 나오는 미미한 오차 제거위해 np.allclose()사용

np.allclose(A@x, B) 

True