## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - **뒷 차원**에서 부터 비교하여 **Shape이 같거나**, 차원 중 **값이 1인 것**이 존재하면 가능
 - (4,3)과 (1,3) 가능
 - (4,3)과 3 가능
 - (4,3)과 (1,4) 불가능
 - (4,3)과 (2,3) 불가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [4]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.47529689 0.38512643 0.50578929 0.96883944 0.88414896]
 [0.32560129 0.37853642 0.88344417 0.35597072 0.76849591]
 [0.41196873 0.56636509 0.25405488 0.9565793  0.73284023]]


In [6]:
x + y

array([[ 0.47529689,  1.38512643,  2.50578929,  3.96883944,  4.88414896],
       [ 5.32560129,  6.37853642,  7.88344417,  8.35597072,  9.76849591],
       [10.41196873, 11.56636509, 12.25405488, 13.9565793 , 14.73284023]])

* Scalar(상수)와의 연산

In [7]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [8]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

* Shape이 다른 경우 연산

In [18]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)  ## 3 벡터
c = b.reshape(1,3)  ## 1X3 행렬
d = np.arange(6).reshape(2,3)  ##안됨

print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[[100 101 102]]
[[0 1 2]
 [3 4 5]]


In [15]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [16]:
a + c

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [19]:
a + d

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 