## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [4]:
import numpy as np

In [6]:
x = np.random.randint(1,101, size=10)
x

array([79, 23, 44, 31, 51, 78,  6, 44, 28, 86])

In [14]:
bool_mask_ndarray = x % 2 == 0 ## 브로드캐스팅 일어나서 가능
bool_mask_ndarray

array([False, False,  True, False, False,  True,  True,  True,  True,
        True])

- bool 리스트를 인덱스로 전달

In [16]:
x[bool_mask_ndarray]  ## True인 원소만 반환

array([44, 78,  6, 44, 28, 86])

In [19]:
x[x % 2 == 0] ## 위와 동일... 조건에 맞는 원소만 반환

array([44, 78,  6, 44, 28, 86])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [20]:
x[(x % 2 == 0) & (x > 30)]

array([44, 78, 44, 86])

In [21]:
x[(x % 2 == 0) | (x > 30)]

array([79, 44, 31, 51, 78,  6, 44, 28, 86])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [26]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [36]:
temp > 25

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [37]:
temp[temp > 25]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [35]:
len(temp[temp > 25]) 
## np.sum(temp > 25)  #true는1, false는 0이므로..

21

In [32]:
np.mean(temp[temp > 25])

26.857142857142858