## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [13]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

#### 연산 함수
 - add, substract, multiply, divide

In [14]:
x = np.arange(20).reshape(4,5)
y = np.random.rand(4,5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.43537057 0.73877583 0.22211092 0.04736761 0.22907845]
 [0.56453897 0.47842488 0.20822701 0.87977327 0.58041963]
 [0.29219548 0.0706949  0.67484309 0.58341994 0.24888363]
 [0.04642883 0.90670085 0.30248111 0.24569705 0.28198096]]


In [15]:
print(x + y)
print(np.add(x,y))

[[ 0.43537057  1.73877583  2.22211092  3.04736761  4.22907845]
 [ 5.56453897  6.47842488  7.20822701  8.87977327  9.58041963]
 [10.29219548 11.0706949  12.67484309 13.58341994 14.24888363]
 [15.04642883 16.90670085 17.30248111 18.24569705 19.28198096]]
[[ 0.43537057  1.73877583  2.22211092  3.04736761  4.22907845]
 [ 5.56453897  6.47842488  7.20822701  8.87977327  9.58041963]
 [10.29219548 11.0706949  12.67484309 13.58341994 14.24888363]
 [15.04642883 16.90670085 17.30248111 18.24569705 19.28198096]]


In [16]:
print(x - y)
print(np.subtract(x,y))

[[-0.43537057  0.26122417  1.77788908  2.95263239  3.77092155]
 [ 4.43546103  5.52157512  6.79177299  7.12022673  8.41958037]
 [ 9.70780452 10.9293051  11.32515691 12.41658006 13.75111637]
 [14.95357117 15.09329915 16.69751889 17.75430295 18.71801904]]
[[-0.43537057  0.26122417  1.77788908  2.95263239  3.77092155]
 [ 4.43546103  5.52157512  6.79177299  7.12022673  8.41958037]
 [ 9.70780452 10.9293051  11.32515691 12.41658006 13.75111637]
 [14.95357117 15.09329915 16.69751889 17.75430295 18.71801904]]


In [17]:
print(x * y)
print(np.multiply(x,y))

[[ 0.          0.73877583  0.44422185  0.14210282  0.91631382]
 [ 2.82269486  2.87054928  1.45758906  7.03818614  5.22377667]
 [ 2.92195477  0.77764392  8.09811708  7.5844592   3.48437078]
 [ 0.69643244 14.50721363  5.14217894  4.42254698  5.35763826]]
[[ 0.          0.73877583  0.44422185  0.14210282  0.91631382]
 [ 2.82269486  2.87054928  1.45758906  7.03818614  5.22377667]
 [ 2.92195477  0.77764392  8.09811708  7.5844592   3.48437078]
 [ 0.69643244 14.50721363  5.14217894  4.42254698  5.35763826]]


In [18]:
print(x / y)
print(np.divide(x,y))

[[  0.           1.35359058   9.00450983  63.33442219  17.46126676]
 [  8.85678447  12.54115378  33.61715671   9.09325198  15.50602277]
 [ 34.22366454 155.59820724  17.78191136  22.28240612  56.25118927]
 [323.07512914  17.64639348  56.20185598  73.26095159  67.38043566]]
[[  0.           1.35359058   9.00450983  63.33442219  17.46126676]
 [  8.85678447  12.54115378  33.61715671   9.09325198  15.50602277]
 [ 34.22366454 155.59820724  17.78191136  22.28240612  56.25118927]
 [323.07512914  17.64639348  56.20185598  73.26095159  67.38043566]]


#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [19]:
x = np.arange(20).reshape(4,5)

In [20]:
np.mean(x)

9.5

In [21]:
np.max(x)

19

In [22]:
np.min(x)

0

In [24]:
np.argmax(x) ## flatten한 상태로 가정하고 인덱스를 반환

19

In [25]:
np.var(x), np.median(x), np.std(x)

(33.25, 9.5, 5.766281297335398)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [26]:
x = np.arange(20).reshape(4,5)

In [27]:
np.sum(x)

190

In [29]:
np.cumsum(x)  ## 누적합

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [37]:
x = np.arange(20).reshape(4,5)

In [38]:
x > 0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [39]:
np.any(x > 0)

True

In [40]:
np.all(x > 0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [43]:
z = np.random.randn(10)
z

array([-5.78383771e-01, -6.07110345e-01,  7.96500664e-04,  1.40291969e+00,
        9.56588011e-01, -1.79880669e+00, -3.19259951e-01,  3.09829216e-01,
        6.74697685e-02, -3.57270446e-01])

In [45]:
## np.where(조건문, 참일때수행, 거짓일때수행)
np.where(z>0, z, 0)


array([0.00000000e+00, 0.00000000e+00, 7.96500664e-04, 1.40291969e+00,
       9.56588011e-01, 0.00000000e+00, 0.00000000e+00, 3.09829216e-01,
       6.74697685e-02, 0.00000000e+00])