### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [2]:
import numpy as np

#### np.array 함수로 생성하기

In [8]:
x = np.array([1,2,3])
print(x)

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

print(type(y))

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,10,2)

array([2, 4, 6, 8])

#### np.ones, np.zeros로 생성하기

In [15]:
np.ones((3,4))  ## 3행 4열의 원소가 모두 1인 행렬

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((3,4,5)) ## 3x4x5인 텐서 생성

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

#### np.empty, np.full로 생성하기

In [23]:
np.empty((3,5)) ## 아무값으로 초기화해줌

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.full((3,4),7)  # 7로만 이루어진 3x4 행렬

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [27]:
np.eye(5)  ## 5x5 대각행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기

In [30]:
np.linspace(1,21,3) ## 1과 21 가운데 차이가 같은 원소로 총 3개 만듦

array([ 1., 11., 21.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [37]:
x = np.arange(1,16)
print(x)  

print(x.shape)

x.reshape(5,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])